export const dish = [
    {
        name:"PHO su jautiena",
        category: "Sriuba",
        en_category: "Soup",
        image:"https://lh3.googleusercontent.com/pw/AIL4fc9rcnSr3wUzcyGLyOIGaXxMU1fzNEeRgFbDl-vv6BRYksvPBPbseYwarkeDgzoQyuD-rdmXHH0I9WJqd1bIgcqnEkBNkV03iThmcM6a-k77-EO4Uy1oYkkzrVWKE1jlkp-yaye8UonrwTCfbal59TKI=w656-h656-s-no?authuser=0",
        en_name:"PHO with beef",
        popular:true,
        price:5,
        description:"Ryžių makaronai, sojos pupelių daigai, jautiena, svogūnai",
        en_description:"Rice noodles, soybean sprouts, beef, onions",
    },
    {
        name:"PHO su vištiena",
        category: "Sriuba",
        en_category: "Soup",
        image:"",
        en_name:"PHO with chicken",
        popular:false,
        price:5,
        description:"Ryžių makaronai, sojos pupelių daigai, vištiena, svogūnai",
        en_description:"Rice noodles, soybean sprouts, chicken, onions",
    },
    {
        name:"MIEN su vištiena",
        category: "Sriuba",
        en_category: "Soup",
        image:"",
        en_name:"MIEN with chicken",
        popular:false,
        price:5,
        description:"Sojos makaronai, sojos pupelių daigai, vištiena, svogūnai",
        en_description:"Soy noodles, soybean sprouts, chicken, onions",
    },
    {
        name:"Aštri sriuba su krevetėmis",
        category: "Sriuba",
        en_category: "Soup",
        image:"",
        en_name:"Spicy soup with shrimps",
        popular:false,
        price:6,
        description:"Brokoliai, paprika, salierai, morkos, krevetės, svogūnai",
        en_description:"Broccoli, paprika, celery, carrots, shrimps, onions",
    },
    {
        name:"Traški vištiena su daržovėmis",
        category: "Vištiena",
        en_category: "Chicken",
        image:"",
        en_name:"Crispy fried chicken with vegetables",
        popular:false,
        price:6.5,
        description:"Ryžiai, vištiena, brokoliai, salierai, saldžioji paprika",
        en_description:"Rice, chicken, broccoli, celery, bell pepper"
    },
    {
        name:"Saldžiarūgštė vištiena su daržovėmis",
        category: "Vištiena",
        en_category: "Chicken",
        image:"",
        en_name:"Sweet and sour chicken with vegetables",
        popular:false,
        price:6.5,
        description:"Ryžiai, vištiena, brokoliai, salierai, saldžioji paprika, ananasų sultys",
        en_description:"Rice, chicken, broccoli, celery, bell pepper, pineapple juice"
    },
    {
        name:"Vištiena su anakardžiais ir žemės riešutais",
        category: "Vištiena",
        en_category: "Chicken",
        image:"",
        en_name:"Chicken with cashew and peanuts",
        popular:false,
        price:6.5,
        description:"Ryžiai, vištiena, brokoliai, salierai, saldžioji paprika, ananasų sultys, anakardžiai, žemės riešutai",
        en_description:"Rice, chicken, broccoli, celery, bell pepper, pineapple juice, cashew, peanuts"
    },
    {
        name:"Kepti ryžiai su vištiena",
        category: "Vištiena",
        en_category: "Chicken",
        image:"",
        en_name:"Fried rice with chicken",
        popular:false,
        price:6.5,
        description:"Ryžiai, vištiena, brokoliai, salierai, saldžioji paprika, traškūs kepti svogūnai, česnakai, sezamo sieklos",
        en_description:"Rice, chicken, broccoli, celery, bell pepper, fried onions, garlic, sesame seeds"
    },
    {
        name:"Kepti MIEN su vištiena",
        category: "Vištiena",
        en_category: "Chicken",
        image:"",
        en_name:"Fried MIEN with chicken",
        popular:false,
        price:6.5,
        description:"Ryžiai, sojos makaronai, vištiena, brokoliai, salierai, saldžioji paprika, morkos, traškūs kepti svogūnai, česnakai, sezamo sėklos",
        en_description:"Rice, soy noodles, chicken, broccoli, celery, bell pepper, carrots, fried onions, garlic, sesame seeds"
    },
    {
        name:"Vištiena kario padaže",
        category: "Vištiena",
        en_category: "Chicken",
        image:"",
        en_name:"Chicken in curry sauce",
        popular:false,
        price:6.5,
        description:"Ryžiai, vištiena, brokoliai, salierai, saldžioji paprika, ananasų sultys, anakardžiai, žemės riešutai",
        en_description:"Rice, chicken, broccoli, celery, bell pepper, pineapple juice, cashew, peanuts"
    },
    {
        name:"Kepta jautiena su daržovėmis",
        category: "Jautiena",
        en_category: "Beef",
        image:"",
        en_name:"Beef with vegetables",
        popular:false,
        price:7.5,
        description:"Ryžiai, jautiena, brokoliai, salierai, saldžioji paprika, morkos, svogūnai, česnakai",
        en_description:"Rice, beef, broccoli, celery, bell pepper, carrots, onions, garlic"
    },
    {
        name:"Kepta jautiena su bambukais",
        category: "Jautiena",
        en_category: "Beef",
        image:"",
        en_name:"Beef with bamboos",
        popular:false,
        price:7.5,
        description:"Ryžiai, jautiena, brokoliai, salierai, saldžioji paprika, morkos, svogūnai, česnakai, bambukai",
        en_description:"Rice, beef, broccoli, celery, bell pepper, carrots, onions, garlic, bamboos"
    },
    {
        name:"Kepta jautiena su grybais",
        category: "Jautiena",
        en_category: "Beef",
        image:"",
        en_name:"Beef with mushrooms",
        popular:false,
        price:7.5,
        description:"Ryžiai, jautiena, brokoliai, salierai, saldžioji paprika, morkos, svogūnai, česnakai, baltieji fungus grybai",
        en_description:"Rice, beef, broccoli, celery, bell pepper, carrots, onions, garlic, white fungus mushrooms"
    },
    {
        name:"Kepti ryžiai su jautiena",
        category: "Jautiena",
        en_category: "Beef",
        image:"",
        en_name:"Fried rice with beef",
        popular:false,
        price:7.5,
        description:"Ryžiai, jautiena, brokoliai, salierai, saldžioji paprika, morkos, svogūnai, česnakai, sezamo sėklos",
        en_description:"Rice, beef, broccoli, celery, bell pepper, carrots, onions, garlic, sesame seeds"
    },
    {
        name:"Traški antis su daržovėmis",
        category: "Kita",
        en_category: "Other",
        image:"https://lh3.googleusercontent.com/pw/AIL4fc_zcSKlhAJwbWZYeerNAddoTxWUF-80BeDmgZMv6f1qDSvbRYKY79q_89YUsyWJ6il0szZqikuKaZjj-ZYpHlKmcpmZUYRRaKPkONkx3TmVCtLPyvTVMKcFTNKt2vNTTdvfdsdn9ZZYIlD-x1mxS-cI=w656-h656-s-no?authuser=0",
        en_name:"Crispy fried duck with vegetables",
        popular:false,
        price:9.5,
        description:"Ryžiai, antiena, brokoliai, salierai, saldžioji paprika, morkos",
        en_description: "Rice, duck, broccoli, celery, bell pepper, carrots"
    },
    {
        name:"Kepta antiena su bambukais",
        category: "Kita",
        en_category: "Other",
        image:"",
        en_name:"Duck with bamboos",
        popular:false,
        price:8.5,
        description:"Ryžiai, antiena, brokoliai, salierai, saldžioji paprika, morkos, bambukai",
        en_description:"Rice, duck, broccoli, celery, bell pepper, carrots, bamboos"
    },
    {
        name:"Kepta antiena su grybais",
        category: "Kita",
        en_category: "Other",
        image:"",
        en_name:"Duck with mushrooms",
        popular:false,
        price:8.5,
        description:"Ryžiai, antiena, brokoliai, salierai, saldžioji paprika, morkos, baltieji fungus grybai",
        en_description:"Rice, duck, broccoli, celery, bell pepper, carrots, white fungus mushrooms"
    },
    {
        name:"Keptos jūros gerybės su daržovėmis",
        category: "Kita",
        en_category: "Other",
        image:"",
        en_name:"Fried seafood with vegetables",
        popular:false,
        price:7.5,
        description:"Ryžiai, jūros gerybės, brokoliai, salierai, saldžioji paprika, morkos, baltieji fungus grybai",
        en_description:"Rice, seafood, broccoli, celery, bell pepper, carrots, white fungus mushrooms"
    },
    {
        name:"Maži aštuonkojai su krevetėmis ir daržovėmis",
        category: "Kita",
        en_category: "Other",
        image:"",
        en_name:"Small octopus with shrimps and vegetables",
        popular:false,
        price:7.5,
        description:"Ryžiai, krevetės, maži aštuonkojai, brokoliai, salierai, saldžioji paprika, morkos, baltieji fungus grybai",
        en_description:"Rice, shrimps, small octopus, broccoli, celery, bell pepper, carrots, white fungus mushrooms"
    },
    {
        name:"Kepta žuvis su daržovėmis",
        category: "Kita",
        en_category: "Other",
        image:"",
        en_name:"Fried fish with vegetables",
        popular:false,
        price:7.5,
        description:"Ryžiai, mažaakių pangasijų filė be odos, brokoliai, salierai, saldžioji paprika, morkos",
        en_description:"Rice, fillet of small-eyed pangasius, broccoli, celery, bell pepper, carrots"
    },
    {
        name:"Krevetės kario padaže su daržovėmis",
        category: "Kita",
        en_category: "Other",
        image:"",
        en_name:"Shrimps in curry sauce with vegetables",
        popular:false,
        price:7.5,
        description:"Ryžiai, krevetės, brokoliai, salierai, saldžioji paprika, morkos, sezamo sėklos, kokoso pienas",
        en_description:"Rice, shrimps, broccoli, celery, bell pepper, carrots, sesame seeds, coconut milk"
    },
    {
        name:"Kepti ryžiai su krevetėmis",
        category: "Kita",
        en_category: "Other",
        image:"",
        en_name:"Fried rice with shrimps",
        popular:false,
        price:7.5,
        description:"Ryžiai, krevetės, brokoliai, salierai, saldžioji paprika, morkos, traškūs kepti svogūnai, česnakai, sezamo sėklos",
        en_description:"Rice, shrimps, broccoli, celery, bell pepper, carrots, fried onions, garlic, sesame seeds"
    },
    {
        name:"NEM",
        category: "Kita",
        en_category: "Other",
        image:"https://lh3.googleusercontent.com/pw/AIL4fc9OQs2uiLRI6VAzXfnm1v4mPLTVkr4HuGtvBHcqYRyWxVagh6qqWlKLnk-sywGYw66SsZMuojYnPgeqmBw2GWNAiGz2aDyQrXxtpCzFuaZPKkU2pm8wFXRr8-VIKdRmPDrsOHmHlVDYwKslnUjpUN-9=w656-h656-s-no?authuser=0",
        en_name:"NEM",
        popular:true,
        price:7.5,
        description: "Vištiena, kopūstas, morkos, sojos makaronai, juodieji fungus grybai, svogūnai, kiaušiniai, ryžių popierius, malti imbierai, prieskoniai",
        en_description: "Chicken, cabbage, carrots, soy noodles, black fungus mushrooms, onions, eggs, rice paper, ground ginger, spices",
    },
    {
        name:"Keptos krevetės su daržovėmis",
        category: "Kita",
        en_category: "Other",
        image:"",
        en_name:"Shrimps with vegetables",
        popular:false,
        price:7.5,
        description:"Krevetės, brokoliai, salierai, saldžioji paprika, morkos, svogūnai, česnakai, baltieji fungus grybai",
        en_description:"Shrimps, broccoli, celery, sweet pepper, carrots, onions, garlic, white fungus mushrooms"
    },
]